---
- name: Restart Keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
  register: _servicerestart
  when:
    - _servicestart is defined and _servicestart is not changed
